USE fpxxl;

ALTER TABLE players COMMENT='玩家账号基础信息表';
ALTER TABLE players
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '玩家自增主键',
  MODIFY COLUMN open_id VARCHAR(128) NOT NULL COMMENT '微信小游戏 openid，业务唯一标识',
  MODIFY COLUMN union_id VARCHAR(128) NULL COMMENT '微信 unionid，满足开放平台条件时可用',
  MODIFY COLUMN nickname VARCHAR(64) NOT NULL DEFAULT '' COMMENT '玩家昵称',
  MODIFY COLUMN avatar_url VARCHAR(512) NOT NULL DEFAULT '' COMMENT '玩家头像地址',
  MODIFY COLUMN status ENUM('active','blocked','deleted') NOT NULL DEFAULT 'active' COMMENT '玩家账号状态：active正常，blocked封禁，deleted删除',
  MODIFY COLUMN last_login_at DATETIME NULL COMMENT '最近登录时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE player_progress COMMENT='玩家进度和资源余额表';
ALTER TABLE player_progress
  MODIFY COLUMN player_id BIGINT UNSIGNED NOT NULL COMMENT '玩家 ID，关联 players.id',
  MODIFY COLUMN current_level INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '当前推进到的关卡编号',
  MODIFY COLUMN coins INT NOT NULL DEFAULT 0 COMMENT '当前金币余额快照',
  MODIFY COLUMN stamina INT NOT NULL DEFAULT 5 COMMENT '当前体力余额快照',
  MODIFY COLUMN max_stamina INT UNSIGNED NOT NULL DEFAULT 5 COMMENT '体力上限',
  MODIFY COLUMN hints INT NOT NULL DEFAULT 0 COMMENT '提示道具数量',
  MODIFY COLUMN level_stars JSON NOT NULL COMMENT '各关卡最高星级 JSON，例如 {"1":3}',
  MODIFY COLUMN completed_levels JSON NOT NULL COMMENT '已通关关卡编号数组 JSON',
  MODIFY COLUMN next_stamina_recover_at DATETIME NULL COMMENT '下一次自然恢复体力时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE level_configs COMMENT='关卡配置表';
ALTER TABLE level_configs
  MODIFY COLUMN level_id INT NOT NULL COMMENT '业务关卡编号',
  MODIFY COLUMN rows_count INT NOT NULL COMMENT '牌阵行数',
  MODIFY COLUMN cols_count INT NOT NULL COMMENT '牌阵列数',
  MODIFY COLUMN pair_count INT NOT NULL COMMENT '配对数量，牌数为 pair_count * 2',
  MODIFY COLUMN mode ENUM('normal','time_limit','step_limit') NOT NULL DEFAULT 'normal' COMMENT '关卡模式：normal普通，time_limit限时，step_limit限步',
  MODIFY COLUMN theme_id VARCHAR(64) NOT NULL DEFAULT 'animal' COMMENT '主题 ID，关联 theme_configs.theme_id',
  MODIFY COLUMN initial_preview_ms INT NOT NULL DEFAULT 2000 COMMENT '开局正面预览时长，单位毫秒',
  MODIFY COLUMN flip_back_delay_ms INT NOT NULL DEFAULT 700 COMMENT '错配后盖回延迟，单位毫秒',
  MODIFY COLUMN level_time_limit_seconds INT NOT NULL DEFAULT 120 COMMENT '本关时间上限，单位秒',
  MODIFY COLUMN max_mismatch_count INT NOT NULL DEFAULT 12 COMMENT '最大错配次数',
  MODIFY COLUMN excellent_step_threshold INT NOT NULL COMMENT '三星优秀步数阈值',
  MODIFY COLUMN normal_step_threshold INT NOT NULL COMMENT '二星普通步数阈值',
  MODIFY COLUMN excellent_time_threshold INT NULL COMMENT '三星优秀时间阈值，单位秒',
  MODIFY COLUMN normal_time_threshold INT NULL COMMENT '二星普通时间阈值，单位秒',
  MODIFY COLUMN time_limit_seconds INT NULL COMMENT '限时模式专用时间限制，单位秒',
  MODIFY COLUMN step_limit INT NULL COMMENT '限步模式专用步数限制',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0停用',
  MODIFY COLUMN version INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '配置版本号，用于客户端缓存更新',
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE theme_configs COMMENT='牌面主题配置表';
ALTER TABLE theme_configs
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主题配置自增主键',
  MODIFY COLUMN theme_id VARCHAR(64) NOT NULL COMMENT '主题业务标识',
  MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '主题名称',
  MODIFY COLUMN asset_base_path VARCHAR(255) NOT NULL DEFAULT '' COMMENT '主题资源基础路径',
  MODIFY COLUMN icon_keys JSON NOT NULL COMMENT '主题内可用牌面图标 key 数组',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0停用',
  MODIFY COLUMN version INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '配置版本号，用于客户端缓存更新',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE ad_frequency_configs COMMENT='广告频控配置表';
ALTER TABLE ad_frequency_configs
  MODIFY COLUMN id TINYINT NOT NULL COMMENT '固定配置 ID',
  MODIFY COLUMN no_interstitial_before_level INT NOT NULL DEFAULT 4 COMMENT '指定关卡前不展示插屏广告',
  MODIFY COLUMN interstitial_every_levels INT NOT NULL DEFAULT 4 COMMENT '每隔多少关允许一次插屏广告',
  MODIFY COLUMN max_interstitial_per_day INT NOT NULL DEFAULT 10 COMMENT '单用户每日最大插屏次数',
  MODIFY COLUMN max_revive_per_level INT NOT NULL DEFAULT 1 COMMENT '单局最大复活次数',
  MODIFY COLUMN banner_enabled_scenes JSON NOT NULL COMMENT '允许展示 Banner 的场景数组',
  MODIFY COLUMN version INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '配置版本号，用于客户端缓存更新',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE ad_placements COMMENT='广告位定义表';
ALTER TABLE ad_placements
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '广告位自增主键',
  MODIFY COLUMN placement_key VARCHAR(64) NOT NULL COMMENT '广告位业务标识',
  MODIFY COLUMN ad_type ENUM('rewarded_video','interstitial','banner') NOT NULL COMMENT '广告类型',
  MODIFY COLUMN scene VARCHAR(64) NOT NULL DEFAULT '' COMMENT '广告所属场景',
  MODIFY COLUMN reward_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '完成广告后奖励类型',
  MODIFY COLUMN reward_amount INT NOT NULL DEFAULT 0 COMMENT '完成广告后奖励数量',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0停用',
  MODIFY COLUMN extra_config JSON NULL COMMENT '广告位扩展配置 JSON',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE level_results COMMENT='关卡结算结果表';
ALTER TABLE level_results
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '结算结果自增主键',
  MODIFY COLUMN player_id BIGINT UNSIGNED NOT NULL COMMENT '玩家 ID，关联 players.id',
  MODIFY COLUMN level_id INT UNSIGNED NOT NULL COMMENT '关卡编号',
  MODIFY COLUMN success TINYINT(1) NOT NULL COMMENT '是否通关成功：1成功，0失败',
  MODIFY COLUMN reason ENUM('completed','time_out','mismatch_limit','quit','unknown') NOT NULL DEFAULT 'unknown' COMMENT '结算原因',
  MODIFY COLUMN steps INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本局步数',
  MODIFY COLUMN mismatch_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本局错配次数',
  MODIFY COLUMN elapsed_ms INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本局耗时，单位毫秒',
  MODIFY COLUMN stars TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本局获得星级',
  MODIFY COLUMN coins_earned INT NOT NULL DEFAULT 0 COMMENT '本局获得金币数量',
  MODIFY COLUMN used_hints INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本局使用提示次数',
  MODIFY COLUMN completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结算时间';

ALTER TABLE reward_grants COMMENT='奖励发放流水表';
ALTER TABLE reward_grants
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '奖励流水自增主键',
  MODIFY COLUMN reward_id VARCHAR(128) NOT NULL COMMENT '奖励唯一 ID，用于幂等去重',
  MODIFY COLUMN player_id BIGINT UNSIGNED NOT NULL COMMENT '玩家 ID，关联 players.id',
  MODIFY COLUMN source ENUM('level_complete','ad','daily','activity','shop','admin') NOT NULL COMMENT '奖励来源',
  MODIFY COLUMN source_ref VARCHAR(128) NOT NULL DEFAULT '' COMMENT '奖励来源引用 ID',
  MODIFY COLUMN reward_type ENUM('coins','stamina','hints','revive','time','steps') NOT NULL COMMENT '奖励类型',
  MODIFY COLUMN amount INT NOT NULL COMMENT '奖励数量',
  MODIFY COLUMN level_id INT UNSIGNED NULL COMMENT '关联关卡编号，可为空',
  MODIFY COLUMN granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '奖励发放时间';

ALTER TABLE coin_transactions COMMENT='金币变动流水表';
ALTER TABLE coin_transactions
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '金币流水自增主键',
  MODIFY COLUMN transaction_no VARCHAR(128) NOT NULL COMMENT '金币流水唯一编号',
  MODIFY COLUMN player_id BIGINT UNSIGNED NOT NULL COMMENT '玩家 ID，关联 players.id',
  MODIFY COLUMN change_amount INT NOT NULL COMMENT '变动数量，正数增加，负数扣减',
  MODIFY COLUMN balance_after INT NOT NULL COMMENT '变动后的金币余额',
  MODIFY COLUMN reason ENUM('level_complete','ad_reward','daily_reward','activity_reward','shop_purchase','refund','admin_adjust') NOT NULL COMMENT '金币变动原因',
  MODIFY COLUMN ref_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '关联来源类型',
  MODIFY COLUMN ref_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '关联来源 ID',
  MODIFY COLUMN note VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE stamina_transactions COMMENT='体力变动流水表';
ALTER TABLE stamina_transactions
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '体力流水自增主键',
  MODIFY COLUMN transaction_no VARCHAR(128) NOT NULL COMMENT '体力流水唯一编号',
  MODIFY COLUMN player_id BIGINT UNSIGNED NOT NULL COMMENT '玩家 ID，关联 players.id',
  MODIFY COLUMN change_amount INT NOT NULL COMMENT '变动数量，正数增加，负数扣减',
  MODIFY COLUMN balance_after INT NOT NULL COMMENT '变动后的体力余额',
  MODIFY COLUMN reason ENUM('level_start','coin_exchange','auto_recover','ad_reward','activity_reward','refund','admin_adjust') NOT NULL COMMENT '体力变动原因',
  MODIFY COLUMN ref_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '关联来源类型',
  MODIFY COLUMN ref_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '关联来源 ID',
  MODIFY COLUMN note VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE shop_products COMMENT='商城商品配置表';
ALTER TABLE shop_products
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商品自增主键',
  MODIFY COLUMN product_key VARCHAR(64) NOT NULL COMMENT '商品业务标识',
  MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '商品名称',
  MODIFY COLUMN product_type ENUM('stamina','item','bundle') NOT NULL COMMENT '商品类型',
  MODIFY COLUMN currency_type ENUM('coins','money','ad') NOT NULL DEFAULT 'coins' COMMENT '支付货币类型',
  MODIFY COLUMN currency_amount INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '支付数量',
  MODIFY COLUMN grant_type ENUM('stamina','hints','coins','bundle') NOT NULL COMMENT '购买后发放类型',
  MODIFY COLUMN grant_amount INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '购买后发放数量',
  MODIFY COLUMN daily_buy_limit INT UNSIGNED NULL COMMENT '每日购买上限，空表示不限',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0停用',
  MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
  MODIFY COLUMN extra_config JSON NULL COMMENT '商品扩展配置 JSON',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE purchase_orders COMMENT='商城购买订单表';
ALTER TABLE purchase_orders
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '订单自增主键',
  MODIFY COLUMN order_no VARCHAR(128) NOT NULL COMMENT '订单唯一编号',
  MODIFY COLUMN player_id BIGINT UNSIGNED NOT NULL COMMENT '玩家 ID，关联 players.id',
  MODIFY COLUMN product_id BIGINT UNSIGNED NOT NULL COMMENT '商品 ID，关联 shop_products.id',
  MODIFY COLUMN product_key VARCHAR(64) NOT NULL COMMENT '商品业务标识快照',
  MODIFY COLUMN product_name VARCHAR(64) NOT NULL COMMENT '商品名称快照',
  MODIFY COLUMN currency_type ENUM('coins','money','ad') NOT NULL COMMENT '支付货币类型',
  MODIFY COLUMN currency_amount INT UNSIGNED NOT NULL COMMENT '支付数量',
  MODIFY COLUMN grant_type ENUM('stamina','hints','coins','bundle') NOT NULL COMMENT '发放类型',
  MODIFY COLUMN grant_amount INT UNSIGNED NOT NULL COMMENT '发放数量',
  MODIFY COLUMN status ENUM('created','paid','fulfilled','cancelled','failed','refunded') NOT NULL DEFAULT 'created' COMMENT '订单状态',
  MODIFY COLUMN paid_at DATETIME NULL COMMENT '支付时间',
  MODIFY COLUMN fulfilled_at DATETIME NULL COMMENT '发放完成时间',
  MODIFY COLUMN failed_reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '失败原因',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE ad_events COMMENT='广告事件日志表';
ALTER TABLE ad_events
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '广告事件自增主键',
  MODIFY COLUMN event_id VARCHAR(128) NOT NULL COMMENT '广告事件唯一 ID',
  MODIFY COLUMN player_id BIGINT UNSIGNED NULL COMMENT '玩家 ID，关联 players.id，可为空',
  MODIFY COLUMN ad_type ENUM('rewarded_video','interstitial','banner') NOT NULL COMMENT '广告类型',
  MODIFY COLUMN placement_key VARCHAR(64) NOT NULL COMMENT '广告位业务标识',
  MODIFY COLUMN status ENUM('requested','shown','completed','closed','failed','reward_granted') NOT NULL COMMENT '广告事件状态',
  MODIFY COLUMN level_id INT UNSIGNED NULL COMMENT '关联关卡编号，可为空',
  MODIFY COLUMN reward_id VARCHAR(128) NULL COMMENT '关联奖励 ID，可为空',
  MODIFY COLUMN error_message VARCHAR(255) NOT NULL DEFAULT '' COMMENT '广告错误信息',
  MODIFY COLUMN payload JSON NULL COMMENT '广告事件扩展数据 JSON',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE leaderboard_entries COMMENT='排行榜成绩表';
ALTER TABLE leaderboard_entries
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '排行榜记录自增主键',
  MODIFY COLUMN player_id BIGINT UNSIGNED NOT NULL COMMENT '玩家 ID，关联 players.id',
  MODIFY COLUMN level_id INT UNSIGNED NOT NULL COMMENT '关卡编号',
  MODIFY COLUMN nickname VARCHAR(64) NOT NULL DEFAULT '' COMMENT '提交时玩家昵称快照',
  MODIFY COLUMN stars TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '星级',
  MODIFY COLUMN steps INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '步数',
  MODIFY COLUMN elapsed_ms INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '耗时，单位毫秒',
  MODIFY COLUMN submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间';

ALTER TABLE game_events COMMENT='通用玩法事件日志表';
ALTER TABLE game_events
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '玩法事件自增主键',
  MODIFY COLUMN event_id VARCHAR(128) NOT NULL COMMENT '玩法事件唯一 ID',
  MODIFY COLUMN player_id BIGINT UNSIGNED NULL COMMENT '玩家 ID，关联 players.id，可为空',
  MODIFY COLUMN event_type VARCHAR(64) NOT NULL COMMENT '事件类型',
  MODIFY COLUMN level_id INT UNSIGNED NULL COMMENT '关联关卡编号，可为空',
  MODIFY COLUMN payload JSON NOT NULL COMMENT '事件扩展数据 JSON',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE player_progress_legacy COMMENT='旧版玩家进度表备份';
ALTER TABLE player_progress_legacy
  MODIFY COLUMN open_id VARCHAR(128) NOT NULL COMMENT '旧版玩家 openid',
  MODIFY COLUMN current_level INT NOT NULL DEFAULT 1 COMMENT '旧版当前关卡',
  MODIFY COLUMN coins INT NOT NULL DEFAULT 0 COMMENT '旧版金币余额',
  MODIFY COLUMN hints INT NOT NULL DEFAULT 0 COMMENT '旧版提示道具数量',
  MODIFY COLUMN level_stars JSON NOT NULL COMMENT '旧版各关卡星级 JSON',
  MODIFY COLUMN completed_levels JSON NOT NULL COMMENT '旧版已通关关卡 JSON',
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '旧版创建时间',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '旧版更新时间';

ALTER TABLE level_results_legacy COMMENT='旧版关卡结算结果表备份';
ALTER TABLE level_results_legacy
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '旧版结算结果自增主键',
  MODIFY COLUMN open_id VARCHAR(128) NOT NULL COMMENT '旧版玩家 openid',
  MODIFY COLUMN level_id INT NOT NULL COMMENT '旧版关卡编号',
  MODIFY COLUMN success TINYINT(1) NOT NULL COMMENT '旧版是否通关成功',
  MODIFY COLUMN reason VARCHAR(32) NOT NULL COMMENT '旧版结算原因',
  MODIFY COLUMN steps INT NOT NULL COMMENT '旧版步数',
  MODIFY COLUMN mismatch_count INT NOT NULL COMMENT '旧版错配次数',
  MODIFY COLUMN elapsed_ms INT NOT NULL COMMENT '旧版耗时，单位毫秒',
  MODIFY COLUMN stars INT NOT NULL COMMENT '旧版星级',
  MODIFY COLUMN coins_earned INT NOT NULL DEFAULT 0 COMMENT '旧版获得金币数量',
  MODIFY COLUMN used_hints INT NOT NULL DEFAULT 0 COMMENT '旧版使用提示次数',
  MODIFY COLUMN completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '旧版结算时间';

ALTER TABLE leaderboard_entries_legacy COMMENT='旧版排行榜成绩表备份';
ALTER TABLE leaderboard_entries_legacy
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '旧版排行榜记录自增主键',
  MODIFY COLUMN open_id VARCHAR(128) NOT NULL COMMENT '旧版玩家 openid',
  MODIFY COLUMN nickname VARCHAR(64) NOT NULL DEFAULT '' COMMENT '旧版玩家昵称快照',
  MODIFY COLUMN level_id INT NOT NULL COMMENT '旧版关卡编号',
  MODIFY COLUMN stars INT NOT NULL COMMENT '旧版星级',
  MODIFY COLUMN steps INT NOT NULL COMMENT '旧版步数',
  MODIFY COLUMN elapsed_ms INT NOT NULL COMMENT '旧版耗时，单位毫秒',
  MODIFY COLUMN submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '旧版提交时间';

ALTER TABLE game_events_legacy COMMENT='旧版通用玩法事件日志表备份';
ALTER TABLE game_events_legacy
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '旧版玩法事件自增主键',
  MODIFY COLUMN event_id VARCHAR(128) NOT NULL COMMENT '旧版事件唯一 ID',
  MODIFY COLUMN open_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '旧版玩家 openid',
  MODIFY COLUMN event_type VARCHAR(64) NOT NULL COMMENT '旧版事件类型',
  MODIFY COLUMN payload JSON NOT NULL COMMENT '旧版事件扩展数据 JSON',
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '旧版创建时间';
