server {
  listen 80;
  listen 443 ssl;
  server_name fpxxl-gameapi.gaintmonster.cn;

  ssl_certificate  /root/aliyun_ssl/fpxxl-gameapi/fpxxl-gameapi.gaintmonster.cn.pem;
  ssl_certificate_key  /root/aliyun_ssl/fpxxl-gameapi/fpxxl-gameapi.gaintmonster.cn.key;

  location / {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9004;
        fastcgi_param SCRIPT_FILENAME /var/www/minigame-api/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        fastcgi_read_timeout 120;
  }

  location ~ /\. { 
        deny all; 
  }

  error_log /data/log/nginx/fpxxl-gameapi.gaintmonster.cn.error.log;
  access_log /data/log/nginx/fpxxl-gameapi.gaintmonster.cn.access.log;
}
